---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - secure: "dywssllR7KcFj2p3oVjdIsooxYH8ZikTHDc8gw/RItEy+KCE6VJ/UJWQ/eKwQ4oihdLhFPTdTKrTqjqoIGrlEIqCNqm9QjAsVIDEQZeffVBPJMOZoB4Ri7SZuhuILPr/29uxU1JwpW6fwMbCkPZ+azwKo1icC9Shtyi1XT24YSyD5f15EZ6q9MRRn0TyP/zEZaFuaQIUxZCHcs23Ukl5YkbsXZbWzqNvFIOfpY63Jkp+WMPFI+do7z9Pt+fVkmuGirgAT+u7TEvS0oW9c+EUjEiX4xJ1yAogyJ/iBHljaNlK3Ox3O85xyG52wLfw7+iD1lRssuvXK5or6VG/ONib3gAaYBdfm9XRYs2dxv1rfakd7MxMsZG7oaqCJ0LISC3CHXvGdd8aZXikJ8W2CgE45XI6qIV7mRV6mTZ+Wad2v7thOagjPYSDvUh4OgbxStGnGJl6jqG1/cJpUGZsm87QKdrLbLpOIDqhEbEiAehnyvPG2es0Q8jVnPu5otKF3awXXFDfeyyD/qdTLCd/U+fsqrHeuZob3u8WUWaeX5G5kVZpkU9okSri4BhLyKjPb+nWZXjDFoJtQf6g+IpggCpwv4qke5Q+l9damDay1+vDGuW9U0i+3P/37eOOATaMFVBSIf3Bjl8qFSqIR6Nd206VZ/C7hlU1EZeI1NejPgWuyO8="
  email: false
