---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "YFBiWyy9x2KFqU7JkoImniRTAEBnUcRYYUFBOR6iz5enUigux29tW5pIlrPV3jJHuCjmoyC5qJaoAFQ3bDx3/zDDs6BlxQNbEzqPcgAND7mwJIi/vaYcv7bLjSiCpHJCKiGpSKhLYXAfeyy6x7CaJ8tsv/1wnUlfkWEI4WHdsz1mWgO1ZAQsNZr0Z1lJ507Qe1KeytBE0Qb5C55v/x14RLdbOCpxvj/th3wPmsakQIpq3l6+Aiq5ORMBRNLvynuMJLGxONIGa5Ove7a1A7sLK9UgB5fNHMakENkNkmTSVz/xDFUVguTKvAfn8DPmsDIhVVsGf96aWLSMLD7NhiATn9TW9/s2v4Ltrkmtffiq9pI9psSRksjSMd5aghg+9DqTGngtt1YMveEtm7SurR0qOiCPOkUYUWht38vHsVENyq0FUJtmqhJCi0FTzLYID2bnA234GiK7XaLQKonMsbufZn8upHUerVH6oKORn1C3lIb3VXCpYbPlS/q1MX9Rtfl0eRGAlVliHcZPEsdRCHRGxIRKpnoMbfdTWPaScwA+ub8ItWSYhWLQEuX3lMINDl7jD9si9FBfDZzE6pV5+O9k4V1HC9usIzAZAoKmTzknwJ81TATFp/+/Dp74+f5tlGwgtHaI0iOmhNt5jKyktKsVKwml0a4gyoF9cDBPgZGmDlQ="
  email: false
