---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="debian" tag="stable"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos" tag="7"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="ubuntu" tag="rolling"
    - image="ubuntu" tag="devel"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"
    - env: image="ubuntu" tag="rolling"
    - env: image="ubuntu" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "geytHva3wlc+zYt1VCoOuqfZ2UvyvgTDw878ga1w8Z+jR97HfPiBHyvqjiAVJPqb1FdMntfNX8Xwj02ElzqSeyqyM/xVkPcyKCEJTsyUCbV8HIZYFf++ZvgY1HdbJQuJOHgOWQAIk+6UG+xr69JSG3vOPXeYlFgjqu2+5d9l/3QceimrGTJPeLJZqbPT7Yr6y8nFmOwdqjnxmIB+KAqGu6BT9OHD8NU5nw52/Lz08h+532rAYI+4cP4tgr7+o3KLOl6vuN+82ujGFC5d5OY0z1GSQ8/MHRN37++mD4kUIW+RGNWb75dmRvZZv/8HnJDROjx4GivusdWihedq5yzGyZof3WniiwrtZrqZHtgNz6oBDWqfDfQ+33Qwwdxe5F2Mydm4CUsGSC1f1ku5kePe/Mb+quQhLNg5tK/aYICb8koYr27bMRhbqhs3aO91h52tZ77feXmLLAml/Ur+J1NNPdlJnDhQ3ZrFKwqpRxcqadvD2LPNrfWMNLFJKqxsY9a+MrhHZFzlqngyBi+CjAtN4kzSl5dYX1AvzW+GxNofvS1tJqqJ7j5HvAV/Qc8RIj1DDZkkunBsrZUYOEFg+7hMHx+ZUVau1EUPL4GExLAhmsvLSJLWHACLy6Xvxw/BDUtCoSFTJjBiv/xYAe7r+pRdMmdRcoQcjYUq/I/Gbg+2N50="
  email: false
