---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: s5S/Mw6MZTN+E2Ms/K+3XSKCXmKvSRB8vF8KQSllCNKLv23+L+e2ojR+mviDROUDT+0zUNju1AcUSNznRPuZFDz2ub1ILdlBDAYKw/OcBJqKNWcaq3nJZ0yk2zXNJyu3wlEfKlG8aNoI56hmSikYzIYhw/igSO/8AmjHhcerXUzFoQy1hY6spbIv7c49VoNv7zEz8fZNpdpGF02hqJydwXaJh6mQ2P+RRww/IGNx2/6SILOCBxkeQ9I5AmJB8rwk1rWhFsvNgh/MoczBDuTWwT9MvAINQXXRGvmuG0d6sOCSnKmcdIc2BfTkbpeB7mF5lR+XXuOJU11tyws10Yl8El0lXcxL418QW7K0U+PYploetOvsI12Hm6Mx70t4FP0ERc3S8RTxcGQcB1Gs5hnyKuGiu3IlwgTFOD12is/iPkKvt6kWLEbsbs5KMOEkfNt43Rr2GYA6myPVMMlIfFb81cScjp6/8oUYOj/hwWb3TMiW86p3Y+/lHQR+KF3ikXmI3coc+e+tGdk3jdCwOYp4qRXc7AvKl+bQ+j/Xug07WF6E2YsJBof5qeoM2AwXY69BWUhQgTTlsUddfcwHSZCwQIMSFhiFaj6nwUtbL23or13WyPN1B9Ovu6v+bqURIzWzhVZzGSP09EU1Nex+nNMoHSq/GleJpjgUgW3njnVQgSg=
  email: false
