---
# tasks file for docker_ce

- name: install apt key
  apt_key:
    url: "{{ docker_ce_apt_key_url }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install docker_ce repository for apt
  apt_repository:
    repo: "{{ docker_ce_apt_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt update cache

- name: install docker_ce repository for dnf/yum
  get_url:
    url: "{{ docker_ce_yum_repositories }}"
    dest: /etc/yum.repos.d/docker_ce.repo
  when:
    - ansible_pkg_mgr in ["dnf", "yum"]

- name: install docker_ce packages
  package:
    name: "{{ docker_ce_packages }}"
    state: present

- name: start and enable docker_ce
  service:
    name: "{{ docker_ce_service }}"
    state: started
    enabled: yes
