---
# tasks file for docker_ce
- name: remove conflicting packages
  package:
    name: "{{ docker_ce_conflicting_packages }}"
    state: absent

- name: install apt key
  apt_key:
    url: "{{ docker_ce_apt_key_url }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install docker_ce repository for apt
  apt_repository:
    repo: "{{ docker_ce_apt_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt update cache

- name: install docker_ce repository for yum
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ item.gpgkey }}"
  loop: "{{ docker_ce_yum_repositories }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "dnf"

- name: install docker pip packages
  pip:
    name: "{{ docker_ce_pip_packages }}"
    state: present

- name: add docker group
  group:
    name: docker
    state: present
    system: yes

- name: install docker_ce
  package:
    name: "{{ docker_ce_packages }}"
    state: present

- name: start and enable docker_ce
  service:
    name: "{{ docker_ce_service }}"
    state: started
    enabled: yes
