---
# handlers file for docker_ce

- name: restart docker_ce
  service:
    name: "{{ docker_ce_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool

- name: apt update cache
  apt:
    update_cache: yes
